nodeLinker: node-modules

packageExtensions:
  "@wxt-dev/module-react@*":
    peerDependencies:
      vite: "*"
  "@fluentui/react-accordion@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-avatar@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-carousel@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-color-picker@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-combobox@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-dialog@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-field@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-list@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-menu@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-nav@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-overflow@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-popover@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-swatch-picker@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-table@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-tabs@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-tag-picker@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-teaching-popover@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-toolbar@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-tree@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-alert@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-checkbox@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-components@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-drawer@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-infobutton@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-infolabel@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-input@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-persona@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-progress@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-radio@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-select@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-skeleton@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-slider@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-spinbutton@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-switch@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-tags@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-textarea@*":
    peerDependencies:
      scheduler: "0.23.0"
  "@fluentui/react-search@*":
    peerDependencies:
      scheduler: "0.23.0"
