name: "🐞 Bug Report"
description: Create a report to help us improve the extension
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - xfox111
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g. Sometimes when generating a password not all character sets are included
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction steps
      description: Precisely describe minimal number of steps that make the bug to appear
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See '...'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. Generated password should include at least one character from every enabled character set
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - "Windows 10 and newer"
        - "Windows 8/8.1"
        - "Windows 7 and older"
        - "MacOS"
        - "Debian or Debian-based"
        - "Other"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser name and version
      placeholder: e.g. Microsoft Edge 119.0.2151.58
      description: Put here your browser's name and version
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension version
      placeholder: e.g. 3.0.0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: dropdown
    id: requested-help
    attributes:
      label: Are you willing to submit a PR for this issue?
      options:
        - "yes"
        - "no"
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: The provided reproduction is a minimal reproducible example of the bug.
          required: true
