name: PR next workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Get version from package.json
        id: get_version
        run: |
          extver=`jq -r ".version" package.json`
          echo "version=$extver" >> "$GITHUB_OUTPUT"

      - uses: dev-build-deploy/release-me@v0.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
          draft: true
          version: v${{ steps.get_version.outputs.version }}
          release-notes: .github/release_description_template.md
